name: Go CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.24.1"

      # Dependencies
      - name: Install dependencies
        run: go mod download

      # Execute tests
      - name: Run tests
        run: go test -v ./...

      # Build script
      - name: Build application
        run: go build -o myapp .
